name: WebbPulse Terraform

on:
  pull_request:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

concurrency:
  group: webbpulse-terraform-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  upload:
    uses: WebbPulse/.github/.github/workflows/terraform-run.yml@v3
    with:
      api-url: https://api.staging.terraform.webbpulse.com
